<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.12" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GdtCreator.Core\GdtCreator.Core.csproj" />
  </ItemGroup>

  <Target Name="StageRunnableAppInProjectDirectory" AfterTargets="Build">
    <ItemGroup>
      <RunnableFiles Include="$(TargetDir)**\*"
                     Exclude="$(TargetDir)ref\**\*;$(TargetDir)*.pdb" />
    </ItemGroup>

    <Copy SourceFiles="@(RunnableFiles)"
          DestinationFiles="@(RunnableFiles->'$(MSBuildProjectDirectory)\%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="true" />
  </Target>
</Project>


